### PR TITLE
make service-list table body scrollable

### PR DESCRIPTION
**Pull request by jtbairdsr**
#24

### CODE REVIEW

**Comment by alanzanattadev** [comment]
Hi,

Thank you for the contribution !

Please attach screenshots showing the difference for me to merge / update the package atom :)

**Comment by eipiminus1** [comment]
Hey, I just tested the branch from @jtbairdsr and took some screenshots. I hope this is what you were looking for. Notice the little scroll bar on the right.
## before
before
## after
after

By the way, great addon. I just started using it but it already proved very handy. Thanks :)

**Comment by alanzanattadev** [comment]
Hi @eipiminus1 thank you for the screenshots, very helpful !

**Comment by rodrigoscc** [comment]
Nice! This was never released though. Had to copy/paste the changes.

**Pull request merged**
